export const GET_GAMES_LOADING = "GET_GAMES_LOADING";
export const GET_GAMES_SUCCESS = "GET_GAMES_SUCCESS";
export const GET_GAMES_ERROR = "GET_GAMES_ERROR";

export const GET_GAMES_BY_ID_LOADING = "GET_GAMES_BY_ID_LOADING";
export const GET_GAMES_BY_ID_SUCCESS = "GET_GAMES_BY_ID_SUCCESS";
export const GET_GAMES_BY_ID_ERROR = "GET_GAMES_BY_ID_ERROR";

export const DELETE_GAMES_LOADING = "DELETE_GAMES_LOADING";
export const DELETE_GAMES_SUCCESS = "DELETE_GAMES_SUCCESS";
export const DELETE_GAMES_ERROR = "DELETE_GAMES_ERROR";

export const ADD_GAMES_LOADING = "ADD_GAMES_LOADING";
export const ADD_GAMES_SUCCESS = "ADD_GAMES_SUCCESS";
export const ADD_GAMES_ERROR = "ADD_GAMES_ERROR";

export const UPDATE_GAMES_LOADING = "UPDATE_GAMES_LOADING";
export const UPDATE_GAMES_SUCCESS = "UPDATE_GAMES_SUCCESS";
export const UPDATE_GAMES_ERROR = "UPDATE_GAMES_ERROR";
